server:
  port: 7777
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
spring:
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5s
    type: caffeine
    cache-names:
      - config
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://116.62.222.97:3306/LibraryProject?useUnicode=true&characterEncoding=utf-8
      username: root
      password: fan6135081
      type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.library.libraryproject.entity
