server:
  port: 7777
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
spring:
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5s
    type: caffeine
    cache-names:
      - config
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://0.0.0.0:3306/LibraryProject?useUnicode=true&characterEncoding=utf-8
      username: example
      password: example
      type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.library.libraryproject.entity
logging:
  level:
    com.library.libraryproject: debug
##此处是为了使用@value注解将配置引入到XxlConfig中，也可以直接中XxlConfig手写相关参数
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://localhost:8680
    ### xxl-job executor address
    executor:
      appname: mktcenter
      ip:
      port: 9888
      ### xxl-job log path
      ##logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      ##logretentiondays: -1
    ### xxl-job, access token
    ##accessToken: